# General Settings
title: Coding with Nadewell
email: nishant.shaligram@gmail.com
description: "WordPress Expert | Passionate System Designer | Eager to Build Scalable Solutions with Innovation"
baseurl: ""
url: ""
#social links
facebook: "https://www.facebook.com/nishant.shaligram1/"
instagram: "https://www.instagram.com/_.nishant1601._/"
twitter:
youtube: "https://www.youtube.com/channel/UCUkLY-Z7ImMtOLtkd25wsnQ"

collections:

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
  - scope:
      path: ""
    values:
      layout: "default"
      is_page: true

plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-youtube
  - jekyll-seo-tag
  - jekyll-sitemap